# config.toml  (repo root)
[paths]
raw = "data/cleaned_telco.csv"        # or data/telco_churn.csv
processed_dir = "data/processed"

[model]
test_size = 0.2
n_clusters = 4
# Use columns that actually exist in your telco dataset:
features = ["tenure", "MonthlyCharges", "TotalCharges", "TotalServicesUsed"]

[quality]
min_rows = 300
